// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_def/com.hy.tech.points002.protobuf.person.proto

package com.hy.tech.points002.protobuf;

public final class Player {
  private Player() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>repeated .Address add = 3;</code>
     */
    java.util.List<com.hy.tech.points002.protobuf.Player.Address> 
        getAddList();
    /**
     * <code>repeated .Address add = 3;</code>
     */
    com.hy.tech.points002.protobuf.Player.Address getAdd(int index);
    /**
     * <code>repeated .Address add = 3;</code>
     */
    int getAddCount();
    /**
     * <code>repeated .Address add = 3;</code>
     */
    java.util.List<? extends com.hy.tech.points002.protobuf.Player.AddressOrBuilder> 
        getAddOrBuilderList();
    /**
     * <code>repeated .Address add = 3;</code>
     */
    com.hy.tech.points002.protobuf.Player.AddressOrBuilder getAddOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      age_ = 0;
      add_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                add_ = new java.util.ArrayList<com.hy.tech.points002.protobuf.Player.Address>();
                mutable_bitField0_ |= 0x00000004;
              }
              add_.add(
                  input.readMessage(com.hy.tech.points002.protobuf.Player.Address.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          add_ = java.util.Collections.unmodifiableList(add_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hy.tech.points002.protobuf.Player.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hy.tech.points002.protobuf.Player.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hy.tech.points002.protobuf.Player.Person.class, com.hy.tech.points002.protobuf.Player.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADD_FIELD_NUMBER = 3;
    private java.util.List<com.hy.tech.points002.protobuf.Player.Address> add_;
    /**
     * <code>repeated .Address add = 3;</code>
     */
    public java.util.List<com.hy.tech.points002.protobuf.Player.Address> getAddList() {
      return add_;
    }
    /**
     * <code>repeated .Address add = 3;</code>
     */
    public java.util.List<? extends com.hy.tech.points002.protobuf.Player.AddressOrBuilder> 
        getAddOrBuilderList() {
      return add_;
    }
    /**
     * <code>repeated .Address add = 3;</code>
     */
    public int getAddCount() {
      return add_.size();
    }
    /**
     * <code>repeated .Address add = 3;</code>
     */
    public com.hy.tech.points002.protobuf.Player.Address getAdd(int index) {
      return add_.get(index);
    }
    /**
     * <code>repeated .Address add = 3;</code>
     */
    public com.hy.tech.points002.protobuf.Player.AddressOrBuilder getAddOrBuilder(
        int index) {
      return add_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      for (int i = 0; i < add_.size(); i++) {
        output.writeMessage(3, add_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      for (int i = 0; i < add_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, add_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hy.tech.points002.protobuf.Player.Person)) {
        return super.equals(obj);
      }
      com.hy.tech.points002.protobuf.Player.Person other = (com.hy.tech.points002.protobuf.Player.Person) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && getAddList()
          .equals(other.getAddList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getAddCount() > 0) {
        hash = (37 * hash) + ADD_FIELD_NUMBER;
        hash = (53 * hash) + getAddList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hy.tech.points002.protobuf.Player.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hy.tech.points002.protobuf.Player.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.hy.tech.points002.protobuf.Player.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hy.tech.points002.protobuf.Player.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hy.tech.points002.protobuf.Player.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hy.tech.points002.protobuf.Player.Person.class, com.hy.tech.points002.protobuf.Player.Person.Builder.class);
      }

      // Construct using com.hy.tech.points002.protobuf.Player.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        if (addBuilder_ == null) {
          add_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          addBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hy.tech.points002.protobuf.Player.internal_static_Person_descriptor;
      }

      public com.hy.tech.points002.protobuf.Player.Person getDefaultInstanceForType() {
        return com.hy.tech.points002.protobuf.Player.Person.getDefaultInstance();
      }

      public com.hy.tech.points002.protobuf.Player.Person build() {
        com.hy.tech.points002.protobuf.Player.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hy.tech.points002.protobuf.Player.Person buildPartial() {
        com.hy.tech.points002.protobuf.Player.Person result = new com.hy.tech.points002.protobuf.Player.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.age_ = age_;
        if (addBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            add_ = java.util.Collections.unmodifiableList(add_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.add_ = add_;
        } else {
          result.add_ = addBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hy.tech.points002.protobuf.Player.Person) {
          return mergeFrom((com.hy.tech.points002.protobuf.Player.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hy.tech.points002.protobuf.Player.Person other) {
        if (other == com.hy.tech.points002.protobuf.Player.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (addBuilder_ == null) {
          if (!other.add_.isEmpty()) {
            if (add_.isEmpty()) {
              add_ = other.add_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAddIsMutable();
              add_.addAll(other.add_);
            }
            onChanged();
          }
        } else {
          if (!other.add_.isEmpty()) {
            if (addBuilder_.isEmpty()) {
              addBuilder_.dispose();
              addBuilder_ = null;
              add_ = other.add_;
              bitField0_ = (bitField0_ & ~0x00000004);
              addBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddFieldBuilder() : null;
            } else {
              addBuilder_.addAllMessages(other.add_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hy.tech.points002.protobuf.Player.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hy.tech.points002.protobuf.Player.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.hy.tech.points002.protobuf.Player.Address> add_ =
        java.util.Collections.emptyList();
      private void ensureAddIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          add_ = new java.util.ArrayList<com.hy.tech.points002.protobuf.Player.Address>(add_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hy.tech.points002.protobuf.Player.Address, com.hy.tech.points002.protobuf.Player.Address.Builder, com.hy.tech.points002.protobuf.Player.AddressOrBuilder> addBuilder_;

      /**
       * <code>repeated .Address add = 3;</code>
       */
      public java.util.List<com.hy.tech.points002.protobuf.Player.Address> getAddList() {
        if (addBuilder_ == null) {
          return java.util.Collections.unmodifiableList(add_);
        } else {
          return addBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public int getAddCount() {
        if (addBuilder_ == null) {
          return add_.size();
        } else {
          return addBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public com.hy.tech.points002.protobuf.Player.Address getAdd(int index) {
        if (addBuilder_ == null) {
          return add_.get(index);
        } else {
          return addBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder setAdd(
          int index, com.hy.tech.points002.protobuf.Player.Address value) {
        if (addBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddIsMutable();
          add_.set(index, value);
          onChanged();
        } else {
          addBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder setAdd(
          int index, com.hy.tech.points002.protobuf.Player.Address.Builder builderForValue) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.set(index, builderForValue.build());
          onChanged();
        } else {
          addBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder addAdd(com.hy.tech.points002.protobuf.Player.Address value) {
        if (addBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddIsMutable();
          add_.add(value);
          onChanged();
        } else {
          addBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder addAdd(
          int index, com.hy.tech.points002.protobuf.Player.Address value) {
        if (addBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddIsMutable();
          add_.add(index, value);
          onChanged();
        } else {
          addBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder addAdd(
          com.hy.tech.points002.protobuf.Player.Address.Builder builderForValue) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.add(builderForValue.build());
          onChanged();
        } else {
          addBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder addAdd(
          int index, com.hy.tech.points002.protobuf.Player.Address.Builder builderForValue) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.add(index, builderForValue.build());
          onChanged();
        } else {
          addBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder addAllAdd(
          java.lang.Iterable<? extends com.hy.tech.points002.protobuf.Player.Address> values) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, add_);
          onChanged();
        } else {
          addBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder clearAdd() {
        if (addBuilder_ == null) {
          add_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          addBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public Builder removeAdd(int index) {
        if (addBuilder_ == null) {
          ensureAddIsMutable();
          add_.remove(index);
          onChanged();
        } else {
          addBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public com.hy.tech.points002.protobuf.Player.Address.Builder getAddBuilder(
          int index) {
        return getAddFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public com.hy.tech.points002.protobuf.Player.AddressOrBuilder getAddOrBuilder(
          int index) {
        if (addBuilder_ == null) {
          return add_.get(index);  } else {
          return addBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public java.util.List<? extends com.hy.tech.points002.protobuf.Player.AddressOrBuilder> 
           getAddOrBuilderList() {
        if (addBuilder_ != null) {
          return addBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(add_);
        }
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public com.hy.tech.points002.protobuf.Player.Address.Builder addAddBuilder() {
        return getAddFieldBuilder().addBuilder(
            com.hy.tech.points002.protobuf.Player.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public com.hy.tech.points002.protobuf.Player.Address.Builder addAddBuilder(
          int index) {
        return getAddFieldBuilder().addBuilder(
            index, com.hy.tech.points002.protobuf.Player.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address add = 3;</code>
       */
      public java.util.List<com.hy.tech.points002.protobuf.Player.Address.Builder> 
           getAddBuilderList() {
        return getAddFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hy.tech.points002.protobuf.Player.Address, com.hy.tech.points002.protobuf.Player.Address.Builder, com.hy.tech.points002.protobuf.Player.AddressOrBuilder> 
          getAddFieldBuilder() {
        if (addBuilder_ == null) {
          addBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.hy.tech.points002.protobuf.Player.Address, com.hy.tech.points002.protobuf.Player.Address.Builder, com.hy.tech.points002.protobuf.Player.AddressOrBuilder>(
                  add_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          add_ = null;
        }
        return addBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.hy.tech.points002.protobuf.Player.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hy.tech.points002.protobuf.Player.Person();
    }

    public static com.hy.tech.points002.protobuf.Player.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.hy.tech.points002.protobuf.Player.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string add = 1;</code>
     */
    java.lang.String getAdd();
    /**
     * <code>string add = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddBytes();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      add_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              add_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hy.tech.points002.protobuf.Player.internal_static_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hy.tech.points002.protobuf.Player.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hy.tech.points002.protobuf.Player.Address.class, com.hy.tech.points002.protobuf.Player.Address.Builder.class);
    }

    public static final int ADD_FIELD_NUMBER = 1;
    private volatile java.lang.Object add_;
    /**
     * <code>string add = 1;</code>
     */
    public java.lang.String getAdd() {
      java.lang.Object ref = add_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        add_ = s;
        return s;
      }
    }
    /**
     * <code>string add = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddBytes() {
      java.lang.Object ref = add_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        add_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, add_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, add_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hy.tech.points002.protobuf.Player.Address)) {
        return super.equals(obj);
      }
      com.hy.tech.points002.protobuf.Player.Address other = (com.hy.tech.points002.protobuf.Player.Address) obj;

      boolean result = true;
      result = result && getAdd()
          .equals(other.getAdd());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADD_FIELD_NUMBER;
      hash = (53 * hash) + getAdd().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hy.tech.points002.protobuf.Player.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hy.tech.points002.protobuf.Player.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        com.hy.tech.points002.protobuf.Player.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hy.tech.points002.protobuf.Player.internal_static_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hy.tech.points002.protobuf.Player.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hy.tech.points002.protobuf.Player.Address.class, com.hy.tech.points002.protobuf.Player.Address.Builder.class);
      }

      // Construct using com.hy.tech.points002.protobuf.Player.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        add_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hy.tech.points002.protobuf.Player.internal_static_Address_descriptor;
      }

      public com.hy.tech.points002.protobuf.Player.Address getDefaultInstanceForType() {
        return com.hy.tech.points002.protobuf.Player.Address.getDefaultInstance();
      }

      public com.hy.tech.points002.protobuf.Player.Address build() {
        com.hy.tech.points002.protobuf.Player.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hy.tech.points002.protobuf.Player.Address buildPartial() {
        com.hy.tech.points002.protobuf.Player.Address result = new com.hy.tech.points002.protobuf.Player.Address(this);
        result.add_ = add_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hy.tech.points002.protobuf.Player.Address) {
          return mergeFrom((com.hy.tech.points002.protobuf.Player.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hy.tech.points002.protobuf.Player.Address other) {
        if (other == com.hy.tech.points002.protobuf.Player.Address.getDefaultInstance()) return this;
        if (!other.getAdd().isEmpty()) {
          add_ = other.add_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hy.tech.points002.protobuf.Player.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hy.tech.points002.protobuf.Player.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object add_ = "";
      /**
       * <code>string add = 1;</code>
       */
      public java.lang.String getAdd() {
        java.lang.Object ref = add_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          add_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string add = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddBytes() {
        java.lang.Object ref = add_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          add_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string add = 1;</code>
       */
      public Builder setAdd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        add_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string add = 1;</code>
       */
      public Builder clearAdd() {
        
        add_ = getDefaultInstance().getAdd();
        onChanged();
        return this;
      }
      /**
       * <code>string add = 1;</code>
       */
      public Builder setAddBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        add_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final com.hy.tech.points002.protobuf.Player.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hy.tech.points002.protobuf.Player.Address();
    }

    public static com.hy.tech.points002.protobuf.Player.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    public com.hy.tech.points002.protobuf.Player.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3msg_def/com.hy.tech.points002.protobuf" +
      ".person.proto\":\n\006Person\022\014\n\004name\030\001 \001(\t\022\013\n" +
      "\003age\030\002 \001(\005\022\025\n\003add\030\003 \003(\0132\010.Address\"\026\n\007Add" +
      "ress\022\013\n\003add\030\001 \001(\tB(\n\036com.hy.tech.points0" +
      "02.protobufB\006Playerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Add", });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Add", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
